
@startuml

actor C1 as "Client"

left to right direction
skinparam packageStyle rectangle

rectangle "World Information System" {

    C1 --> (Display all the largest population Countries to the smallest over the world)
    C1 --> (Display all the largest population Countries to smallest in a continent)
    C1 --> (Display all the largest population region to smallest in all countries)
    C1 --> (Display the top populated countries over the world)
    C1 --> (Display the top populated countries in a continent)
    C1 --> (Display the top populated region in all countries)
    C1 --> (Display all the largest population Cities to smallest over the world)
    C1 --> (Display all the largest population Cities to smallest in a continent)
}

@enduml